# Generated by Django 4.0.4 on 2022-06-03 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AreaConhecimento',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('matricula', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('idade', models.IntegerField()),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=200)),
                ('carga_horaria', models.IntegerField()),
                ('periodo', models.IntegerField()),
                ('contagem_periodo', models.CharField(max_length=10)),
                ('ano_oferta', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
                ('fim', models.DateField()),
                ('ano_semestre', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='DiarioAlunos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno_fk', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='escolar.aluno')),
                ('diario_fk', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='escolar.diario')),
            ],
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestor', models.BooleanField()),
                ('cadastro_fk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='escolar.cadastro')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_conhecimento_fk', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='escolar.areaconhecimento')),
                ('cadastro_fk', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='escolar.cadastro')),
            ],
        ),
        migrations.CreateModel(
            name='FaltasDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_presenca', models.DateField()),
                ('presenca', models.BooleanField()),
                ('diario_alunos_fk', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='escolar.diarioalunos')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('carga_horaria', models.IntegerField()),
                ('area_conhecimento_fk', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='escolar.areaconhecimento')),
                ('curso_fk', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='escolar.curso')),
                ('professor_fk', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='escolar.professor')),
            ],
        ),
        migrations.AddField(
            model_name='diario',
            name='disciplina_fk',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='escolar.disciplina'),
        ),
        migrations.AddField(
            model_name='diario',
            name='professor_fk',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='escolar.professor'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='cadastro_fk',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='escolar.cadastro'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='curso_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escolar.curso'),
        ),
    ]
