# Generated by Django 4.0.4 on 2022-06-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolar', '0002_aula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='matricula',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='codigo',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
